Release 3.0.0
nf-core/nanoseq pull request #161
Opened 2022-01-26 09:12 UTC by yuukiiwa

Release 3.0.0

- new DSL2 syntax
- Azure bug fix
- DNA structural variant detection
- RNA modification and fusion detection
- output demultiplexed `fast5`

## PR checklist

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
    - [x] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/nanoseq/tree/master/.github/CONTRIBUTING.md)
    - [x] If necessary, also make a PR on the nf-core/nanoseq _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [x] Make sure your code lints (`nf-core lint`).
- [x] Ensure the test suite passes (`nextflow run . -profile test,docker`).
- [x] Usage Documentation in `docs/usage.md` is updated.
- [x] Output Documentation in `docs/output.md` is updated.
- [x] `CHANGELOG.md` is updated.
- [x] `README.md` is updated (including new tool citations and authors/contributors).

2022-02-01 08:55 UTC, christopher-hakkaart requested changes
It looks pretty good. Most of the comments are moving/correcting the version reporting for sniffles and medaka, couple of small typos, and a .view() left over from debugging (I assume).

Really great!

2022-02-01 08:55 UTC, christopher-hakkaart commented on subworkflows/local/dna_variant_calling.nf
> +    ch_sv_calls = Channel.empty()
```suggestion
    ch_sv_calls = Channel.empty()
    sniffles_version = Channel.empty()
```

2022-02-01 08:55 UTC, christopher-hakkaart commented on nextflow_schema.json
> +                    "description": "Wether to trim the barcodes from the output sequences in the FastQ files from Guppy basecaller."
```suggestion
                    "description": "Whether to trim the barcodes from the output sequences in the FastQ files from Guppy basecaller."
```

2022-02-01 08:55 UTC, christopher-hakkaart commented on nextflow_schema.json
> +                    "description": "Output emultiplex fast5 files with demux_fast5.",
```suggestion
                    "description": "Demultiplex fast5 files with demux_fast5.",
```

2022-02-03 05:16 UTC, yuukiiwa commented on docs/output.md
> +[Guppy](https://nanoporetech.com/nanopore-sequencing-data-analysis), [demux_fasat5](https://github.com/nanoporetech/ont_fast5_api#demux_fast5), [qcat](https://github.com/nanoporetech/qcat)
I have changed this to fast5

2022-02-03 05:18 UTC, yuukiiwa commented on docs/output.md
> +* `minimap2/sniffles/<sample>_sniffles.vcf`
I have changed this to `SAMPLE`. (I can't commit the suggestions because I don't have write access to `dev`)

2022-02-03 05:18 UTC, yuukiiwa commented on docs/output.md
> +*demux_fasat5* will demultiplex the fast5 files, gives the *Guppy* summary file.
Yes, I have changed this to fast5

2022-02-03 05:23 UTC, yuukiiwa commented on nextflow_schema.json
> +                    "description": "Output emultiplex fast5 files with demux_fast5.",
I have changed this accordingly

2022-02-03 05:23 UTC, yuukiiwa commented on nextflow_schema.json
> +                    "description": "Wether to trim the barcodes from the output sequences in the FastQ files from Guppy basecaller."
I have fixed this typo

2022-02-03 05:26 UTC, yuukiiwa commented on subworkflows/local/dna_variant_calling.nf
> +    ch_variant_calls = Channel.empty()
I have added medaka_version

2022-02-03 05:26 UTC, yuukiiwa commented on subworkflows/local/dna_variant_calling.nf
> +    ch_sv_calls = Channel.empty()
I have added `sniffles_version`

2022-02-03 05:28 UTC, yuukiiwa commented on workflows/nanoseq.nf
> +            ch_medaka_version = Channel.empty()
I have removed `ch_medaka_version`

2022-02-03 05:28 UTC, yuukiiwa commented on workflows/nanoseq.nf
> +            ch_sniffles_version = Channel.empty()
I have removed `ch_sniffles_version`

2022-02-03 05:29 UTC, yuukiiwa commented on subworkflows/local/dna_variant_calling.nf
> +        ch_variant_calls = MEDAKA_VARIANT.out.variant_calls
I have added `medaka_version = MEDAKA_VARIANT.out.versions`

2022-02-03 05:29 UTC, yuukiiwa commented on subworkflows/local/dna_variant_calling.nf
> +        ch_sv_calls = SNIFFLES.out.sv_calls
I have added `sniffles_version = SNIFFLES.out.versions`

2022-02-03 05:30 UTC, yuukiiwa commented on subworkflows/local/dna_variant_calling.nf
> +    ch_sv_calls
I have added `sniffles_version` and `medaka_version`

2022-02-03 05:32 UTC, yuukiiwa commented on workflows/nanoseq.nf
>          }
I have added the two lines

2022-02-03 05:38 UTC, yuukiiwa commented on docs/usage.md
> +| `input_file`    | Full path to FastQ file if previously demultiplexed or a BAM file if previously aligned or a path to a directory with subdirectories `fastq` and `fast5` for RNA modification detec
Thank you for the fix!! I have changed this with your sentence

2022-02-04 08:12 UTC, christopher-hakkaart reviewed
I think all the changes I suggested are addressed. Are there any last minute changes/bugs you wanted addressed in dev before we approve the merge?

2022-05-18 13:41 UTC, closed without merging