remove guppy
nf-core/nanoseq pull request #217
Opened 2023-02-15 06:11 UTC by yuukiiwa

Removing guppy as nanopore would provide the basecalled fastq together with the fast5 file. Will have to update the subway map.

2023-02-16 12:40 UTC, christopher-hakkaart requested changes
Looks good. I'll go through the repo for references to basecalling and change the subway map

2023-02-16 12:40 UTC, christopher-hakkaart commented on conf/base.config
> -
This should be kept for deepvariant

2023-02-16 12:40 UTC, christopher-hakkaart commented on nextflow.config
> -    gpu_cluster_options        = null
Should also be kept here

2023-02-16 12:40 UTC, christopher-hakkaart commented on nextflow_schema.json
> -                },
Keep this too.

2023-02-17 05:29 UTC, yuukiiwa commented on nextflow.config
> -    gpu_cluster_options        = null
I have added this back in

2023-02-17 05:31 UTC, yuukiiwa commented on conf/base.config
> -
I have added this back in

2023-02-17 05:31 UTC, yuukiiwa commented on nextflow.config
> -    gpu_cluster_options        = null
I have added this back in

2023-02-17 07:49 UTC, yuukiiwa commented on nextflow_schema.json
> -                },
I have added this back in

2023-02-17 12:46 UTC, christopher-hakkaart approved these changes
Still need to tidy up changelog and some references to basecalling but code looks good.

2023-02-17 12:47 UTC, merged